site_name: Sistemas de banco de dados
nav:
  - Home: index.md
  - Módulo 1 - Modelagem:
    - Parte 1: mod_1/mod1_1.md
    - Parte 2: mod_1/mod1_2.md
  - Módulo 2 - Linguagem SQL DDL:
    - Parte 1: mod_2/mod2_1.md
    - Trbalho 2: mod_2/trab_2.md

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.footer
    - toc.follow
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: pt-BR
  favicon: assets/logounb_doc.svg
  logo: assets/logounb_doc.svg
  palette:
    - scheme: default
      toggle:
        icon: material/globe-light
        name: Dark mode
      primary: #0070f3
      accent: grey
    - scheme: slate
      toggle:
        icon: material/globe-light-outline
        name: Light mode
      primary: #0070f3
      accent: #0070f3
  extra_css:
    - css/custom.css

markdown_extensions:
  - attr_list

extra:
  assets:
    - docs/assets